# Chapter 0
### Resource 
https://www.learnpytorch.io/00_pytorch_fundamentals/#who-uses-pytorch

In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors
### Creating Tensors
PyTorch tensors are created using `torch.Tensor()` 

In [3]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])

In [7]:
print(vector.shape)
print(vector.ndim)


torch.Size([2])
1


In [8]:
#MATRIX
MATRIX = torch.tensor([[7,9],[9,10]])
print(MATRIX.shape)
print(MATRIX.ndim)

torch.Size([2, 2])
2


In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
# TENSOR
TENSOR = torch.tensor([
    [[1,2,3],
     [4,5,6],
     [4,5,6],
     [7,8,9]],

    [[12,12,12],
     [12,12,12],
     [12,12,12],
     [12,12,12]]
])

print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([2, 4, 3])
3


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [11]:
# Create a random tesnor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor.shape

torch.Size([3, 4])

In [12]:
# Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [13]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
# ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [16]:
# Use arange func and get deprecated msg, use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
torch.arange(start=0, end=11, step=1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Tensors-like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data types 

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors are not right datatype
2. Tensors are not right shape
3. Tensors are not on the right device

Precision: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [19]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) #  requires_grad: whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (attributes)
- `tensor.dtype` -> to get a datatype from a tensor
- `tensor.shape` -> to get shape
- `tensor.device` -> to get device information 



In [24]:
# create a tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6255, 0.1186, 0.9069, 0.5447],
        [0.8090, 0.9344, 0.0072, 0.2325],
        [0.7907, 0.7335, 0.4710, 0.5829]])

In [25]:
# Find out details about some tensor
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")

tensor([[0.6255, 0.1186, 0.9069, 0.5447],
        [0.8090, 0.9344, 0.0072, 0.2325],
        [0.7907, 0.7335, 0.4710, 0.5829]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [26]:
# addition
tensor = torch.tensor([1,2,3,])
tensor + 10

tensor([11, 12, 13])

In [27]:
# multiply
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [28]:
# divide
tensor / 2

tensor([ 5., 10., 15.])

In [29]:
# substract
tensor - 100

tensor([-90, -80, -70])

In [30]:
# in-built functions
torch.mul(tensor,10)
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix Multiplication
Two main ways of performing multiplication in NNs and DL:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

Main rules for Matrix Multi:
1. The **inner_dimension** must match:
* `(3, 2) @ (3, 2)` won't work 
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (3,2)` -> `(2,2)` 


In [31]:
# Element-wise multiplicatioan
tensor = torch.tensor([1,2,3])
tensor * tensor

tensor([1, 4, 9])

In [32]:
%%time
torch.matmul(tensor,tensor) #matmul

CPU times: user 81 µs, sys: 58 µs, total: 139 µs
Wall time: 143 µs


tensor(14)

In [33]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

CPU times: user 430 µs, sys: 0 ns, total: 430 µs
Wall time: 307 µs


### Common errors in DL: Shape Error


In [34]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_C = torch.tensor([[7,8,9],
                         [10,11,12]])
torch.matmul(tensor_A,tensor_C)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [35]:
# Transpose
# To fix our tensor shape
# a transpose switches the axes or dimensions of a given tensor
tensor_D = tensor_B.T
tensor_D

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [36]:
torch.matmul(tensor_A,tensor_D), torch.matmul(tensor_A,tensor_D).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [37]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min max mean sum (tensor aggregation)


In [38]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# min
torch.min(x), x.min()


(tensor(0), tensor(0))

In [40]:
# max
torch.max(x)

tensor(90)

In [41]:
# sum
torch.sum(x)

tensor(450)

In [42]:
# mean requires a tensor of float32 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding positional min and max

In [43]:
# find position(index) of min value and max value
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

## Reshaping, viewing and stacking, squeezing, unsqueezing and permuting
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same theory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a target tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way
  

In [44]:
# tensor
import torch 
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# chaning z changes x (beucase a view of a tensor shares the same memory as the original input)
z[:,3] = 8
z, z.shape, x, x.shape

(tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 8., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [48]:
# stack tensors on top of each 
x_stack = torch.stack([x,x,x,x], dim=1)
x_stack, x_stack.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [8., 8., 8., 8.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [49]:
# squeeze
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [50]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [51]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [52]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [53]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([1., 2., 3., 8., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 8., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [56]:
# And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 8., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [8.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])

New tensor: tensor([[1., 2., 3., 8., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [57]:
# torch.permute 
x = torch.randn(2,3,5)
x.size(), x

(torch.Size([2, 3, 5]),
 tensor([[[-0.3167, -0.7588, -1.3503,  1.7389,  1.3304],
          [-1.3733,  0.7764, -2.4009, -0.5762,  0.7264],
          [ 0.5616, -0.8256,  0.2472, -0.2611,  0.1358]],
 
         [[ 0.1201, -1.6495, -0.4839,  0.3610, -1.3186],
          [-1.3355, -1.1548, -0.6106, -0.8188,  0.0039],
          [ 1.1297, -0.9257, -0.3568, -0.8492, -0.2521]]]))

In [58]:
torch.permute(x,(2,0,1)).size() 

torch.Size([5, 2, 3])

In [59]:
x_org = torch.rand(size=(224,224,3))
torch.permute(x_org,(2,0,1)).size() # shifts axis 0->1, 1->2, 2->0

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)
Indexing with pytorch is similar to indexing with numpy

In [60]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
# index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
# index middle bracket
x[0,0]

tensor([1, 2, 3])

In [63]:
x[0][2][1]

tensor(8)

In [64]:
# : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [65]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
# get all values of 0th but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [67]:
x[:,2,2]

tensor([9])

## PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are: 
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor. 
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

In [68]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
array.dtype

dtype('float64')

In [70]:
# change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [71]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [72]:
# change the tensor, what happens to numpy tensor
tensor = tensor +1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
trying to take random out of random

In short, how NNs learn: 

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again..`

To reduce the randomness in NNs and PyTorch comes the comcept of **random seed**.


In [73]:
#import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8560, 0.4977, 0.4101, 0.3399],
        [0.1006, 0.4462, 0.0105, 0.4448],
        [0.8271, 0.6200, 0.7080, 0.2471]])
tensor([[0.5692, 0.0801, 0.3659, 0.0893],
        [0.2500, 0.5021, 0.3978, 0.4557],
        [0.8597, 0.2329, 0.2464, 0.8906]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [74]:
# random but reproducible tensors
# set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED) # İt only works one code block. so thats why we add again in below 
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on GPUs
Make things faster


In [75]:
# gpu availability
!nvidia-smi

Thu Feb 19 10:35:55 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.15              Driver Version: 570.86.15      CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off |   00000000:2D:00.0  On |                  N/A |
| 28%   36C    P8             27W /  260W |     539MiB /  11264MiB |     24%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [76]:
# check with pytorch
import torch
torch.cuda.is_available()

True

In [77]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
# count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the gpu


In [79]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [80]:
# move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [81]:
### moving tensors back to the cpu
# if tensor is on gpu, cant transform it to numpy
tensor_on_gpu.to("cpu").numpy()

array([1, 2, 3])

In [82]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

# Exercises

Create a random tensor with shape (7, 7).

In [83]:
import torch
tensor_a = torch.rand(7,7)
tensor_a

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [84]:
tensor_b = torch.rand(1,7)
result = torch.matmul(tensor_a, tensor_b.T)
result, result.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [101]:
import torch

RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
tensor_a = torch.rand(7,7)
tensor_b = torch.rand(1,7)
result = torch.matmul(tensor_a, tensor_b.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [107]:
torch.cuda.manual_seed(1234)

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [108]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [111]:
# Set random seed
torch.manual_seed(1234)
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [115]:
res = torch.matmul(tensor_A, tensor_B.T)
res

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

Find the maximum and minimum values of the output of 7.

In [118]:
torch.max(res), torch.min(res)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

Find the maximum and minimum index values of the output of 7.

In [120]:
torch.argmax(res), torch.argmin(res)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [126]:
torch.manual_seed(7)
tensor_rand = torch.rand(size=(1,1,1,10))
tensor_rand, tensor_rand.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [129]:
squeezed=torch.squeeze(tensor_rand)
squeezed, squeezed.shape


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))